apiVersion: v1
data:
  loginConfig: |
    PORT=5000
    #ZIPKIN_SERVER_URL=https://vl-devops01.ibaset.com/diagnostics
    # TOKEN_SECRET is injected as K8S secret from deployment file
    SERVICE_NAME=login
    APP_HOST_NAME=https://vl-devops01.ibaset.com
    SSO_ENABLE=--SSO_ENABLED--
    KERBEROS_ENABLE=false
    DEBUG=error:login:*
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: login-cm
